Fix task counts for tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,17 +50,16 @@ jobs:
           echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
 
           echo "Coverage Warnings - ${{ steps.coverageComment.outputs.warnings }}"
-
           echo "Coverage Errors - ${{ steps.coverageComment.outputs.errors }}"
           echo "Coverage Failures - ${{ steps.coverageComment.outputs.failures }}"
           echo "Coverage Skipped - ${{ steps.coverageComment.outputs.skipped }}"
           echo "Coverage Tests - ${{ steps.coverageComment.outputs.tests }}"
           echo "Coverage Time - ${{ steps.coverageComment.outputs.time }}"
-
           echo "Not Success Test Info - ${{ steps.coverageComment.outputs.notSuccessTestInfo }}"
 
-          if [ "${{ steps.coverageComment.outputs.failures }}" != 0 ]; then
-            core.setFailed("Test failures detected!")
+          if [ "${{ steps.coverageComment.outputs.failures }}" != "0" ]; then
+            echo "Test failures detected!"
+            exit 1
           fi
 
       - name: Create Coverage PR Comment
